# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4322ae8f872b7bc339af89acfba30ac36c82a2e7d61a2504433a678e58d003ee2ec38c9cf9672fa4a55fe940167c85f18f866da85f74bb453faf692dca338b82

test:
  secret_key_base: 617b039fd74232924e917a386842e2c6f01140db83b4ec3d2a1aeb57d1003370433eb7f0c4df2612b2416ee351c45e83b370836c7468cad39e57af0be480760e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
